name: My First Workflow

on: 
  workflow_dispatch:
  schedule:
    - cron: "1 15 * 1 *" 
    - cron: "1 15 * 1 1"
  repository_dispatch:
    type: [yearly]

permissions:
  contents: read

env:
  MY_ENV_VAR: Test

jobs:
  echo-hello-world:
    name: Echo Hello World
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: Test
    steps:
      - name: Hello Plusnet
        run: | 
          echo "Hello Plusnet ${{ github.ref }}"
          echo "Hello Plusnet ${{ MY_ENV_VAR }}"
        env:
          MY_ENV_VAR: Test
      - name: Dump GitHub Context
        run: echo '${{ toJSON(github) }}'
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Creating GitHub Output
        run: echo "demo=Plusnet" >> $GITHUB_OUTPUT
        id: github-output
      - name: Using GitHub Output
        run: echo "${{ steps.github-output.outputs.demo }}"
        
